OpenPetra:
    MainMenu:
        # to activate the plugin
        Custom: {Label=Favoriten, Icon=partner.ico, DependsOnLedger=true}
            Favoriten: {DontShowNestedTasksAsLinks=true}
                Spendenbuchhaltung: {Namespace=Ict.Petra.Client.MFinance.Gui.Gift, DontShowNestedTasksAsLinks=true}
                        NewDonorSubscriptions: {Description: "Briefe an Erstspender, mit Ankündigung der Zeitschrift", Namespace=Ict.Petra.Plugins.NewDonorSubscriptions.Client, ActionOpenScreen=TFrmGiftNewDonorLetter, Label="Erstspender Briefe", PermissionsRequired=FINANCE-1}

